# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "puppetlabs_debian_607_x64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/debian-607-x64-vbox4210-nocm.box"

  # Set hostname
  config.vm.hostname = "glu-tutorial"
  
  # Forward ports

  # console 
  config.vm.network :forwarded_port, guest: 8080, host: 8080

  # webapp1
  config.vm.network :forwarded_port, guest: 9000, host: 9000

  # webapp2
  config.vm.network :forwarded_port, guest: 9001, host: 9001

  # webapp3
  config.vm.network :forwarded_port, guest: 9002, host: 9002

  # Set system settings
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end

  config.vm.provision :shell, :path => "install-glu.sh"
end
