<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2010-2010 LinkedIn, Inc
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License"); you may not
  ~ use this file except in compliance with the License. You may obtain a copy of
  ~ the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  ~ WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  ~ License for the specific language governing permissions and limitations under
  ~ the License.
  -->

<ivy-module version="2.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="http://ant.apache.org/ivy/schemas/ivy.xsd">

  <info organisation="test.agent.impl" module="myArtifact" revision="1.0.0"/>

  <configurations>
    <conf name="default"/>
    <conf name="text"/>
  </configurations>

  <publications>
    <artifact conf="default" name="myArtifact" type="jar"/>
    <artifact conf="text" name="myArtifact" type="txt"/>
  </publications>

</ivy-module>
